### ISSUE TITLE
Bringing FFC onto the generic Image Service

### ISSUE THREAD

**Issue by philsturgeon** [GreenTurtleTech/image-service#2]
Requirements have simplified, so please can we ditch the FFC custom lambda and get this generic image-service deployed for them? 

1. Make supervisor optional, FFC do not use it
2. Let's bring back the device ID they use, and pass it onto the API.
3. API will need to save device ID and be ok with supervisor being optional.
4. Can we remove any ENV settings that default to PE buckets or anything like that, and document what needs doing to set them so we can make sure there's no crossover?

Would be amazing to get #1 done as part of this so we all know how things are meant to work.

**Comment by Shelob9** [comment]
Some notes to self on this:

- Currently there is a Github action that takes env vars for two things and does deploy. Those two things are:
 - Set up AWS Account
 - Set which bucket and API endpoint are used.
- As-is, no way to support two or more clients without forking.
 - Best to have one code base that deploys with different sets of variables.
- Idea:
  - One repo, multiple Github actions. 
  - We set secrets in this repo with prefixes `PE_GITHUB_ACCOUNT_ID`, `FFC_TREE_API_URL`, `OTHERCLIENT_ACCOUNT_ID` 
  - We have one Github action per client using this repo, that way we can roll out the same changes to each, or we can customize each deployment as needed.

**Comment by Shelob9** [comment]
@philsturgeon What does `API will need to save device ID and be ok with supervisor being optional.` mean? Is this new metadata?

**Comment by philsturgeon** [comment]
New to tree tracker, but it’s something FFC was sending previously. Can you nip it out of the old lambda and put it in the docs so the iOS app can send it? It should be optional.

**Comment by Shelob9** [comment]
@philsturgeon I don't see device ID anywhere in there old lambda. I can add support, just need to know what the meta field's name will be.

**Comment by philsturgeon** [comment]
Ah they used to call it `userId: string`. Let's call it `deviceId` because that's what it is.

**Comment by philsturgeon** [comment]
@Shelob9 for context I've added device_id (optional) and made supervisor optional too in this pull request. https://github.com/GreenTurtleTech/tree-tracker-web/pull/126/files
